import type { FallingPreset } from "./types.js";

export const FALLING_PRESETS: FallingPreset[] = [
  {
    id: "snow",
    name: "Snow",
    category: "falling",
    description: "Gentle snowfall with mixed flake sizes drifting in light wind",
    tags: ["winter", "snow", "cold", "gentle"],
    particleType: "snowflake",
    count: 200,
    sizeMin: 2,
    sizeMax: 8,
    color: "#FFFFFF",
    colorVariation: 0.05,
    opacity: 0.8,
    windAngle: 15,
    windStrength: 0.3,
    windTurbulence: 0.15,
    fallProgress: 0.7,
    fallSpreadY: 0.3,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "rain",
    name: "Rain",
    category: "falling",
    description: "Steady rainfall with elongated drops and consistent direction",
    tags: ["rain", "storm", "wet", "dramatic"],
    particleType: "raindrop",
    count: 400,
    sizeMin: 3,
    sizeMax: 10,
    color: "#B0C4DE",
    colorVariation: 0.1,
    opacity: 0.5,
    windAngle: 5,
    windStrength: 0.1,
    fallProgress: 1.0,
    depthDistribution: "uniform",
    depthEasing: "quadratic",
    horizonY: 0.25,
  },
  {
    id: "autumn-leaves",
    name: "Autumn Leaves",
    category: "falling",
    description: "Drifting autumn leaves in warm colors tumbling in gusty wind",
    tags: ["autumn", "leaves", "warm", "seasonal"],
    particleType: "leaf",
    count: 60,
    sizeMin: 6,
    sizeMax: 18,
    color: "#C8652A",
    colorVariation: 0.3,
    opacity: 0.9,
    windAngle: 25,
    windStrength: 0.5,
    windTurbulence: 0.5,
    fallProgress: 0.5,
    fallSpreadY: 0.6,
    depthDistribution: "foreground-heavy",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "petals",
    name: "Cherry Blossom Petals",
    category: "falling",
    description: "Delicate pink petals drifting and swirling on a spring breeze",
    tags: ["spring", "petals", "cherry", "delicate"],
    particleType: "petal",
    count: 80,
    sizeMin: 4,
    sizeMax: 12,
    color: "#FFB7C5",
    colorVariation: 0.15,
    opacity: 0.85,
    windAngle: 30,
    windStrength: 0.4,
    windTurbulence: 0.35,
    fallProgress: 0.4,
    fallSpreadY: 0.5,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.35,
  },
  {
    id: "embers",
    name: "Embers",
    category: "falling",
    description: "Glowing hot embers rising and drifting from a fire",
    tags: ["fire", "embers", "warm", "night", "glow"],
    particleType: "ember",
    count: 50,
    sizeMin: 2,
    sizeMax: 6,
    color: "#FF6600",
    colorVariation: 0.25,
    opacity: 0.9,
    windAngle: -10,
    windStrength: 0.2,
    fallProgress: 0.6,
    depthDistribution: "foreground-heavy",
    depthEasing: "linear",
    horizonY: 0.5,
  },
  {
    id: "ash-fall",
    name: "Ash Fall",
    category: "falling",
    description: "Grey volcanic ash drifting down in still air",
    tags: ["ash", "volcanic", "grey", "slow"],
    particleType: "ash",
    count: 150,
    sizeMin: 2,
    sizeMax: 7,
    color: "#888888",
    colorVariation: 0.2,
    opacity: 0.6,
    windAngle: 5,
    windStrength: 0.15,
    fallProgress: 0.8,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "cherry-blossoms",
    name: "Cherry Blossoms",
    category: "falling",
    description: "Dense shower of cherry blossoms in a spring storm",
    tags: ["spring", "cherry", "blossoms", "dense", "pink"],
    particleType: "petal",
    count: 200,
    sizeMin: 5,
    sizeMax: 14,
    color: "#FFB0C0",
    colorVariation: 0.2,
    opacity: 0.9,
    windAngle: 35,
    windStrength: 0.6,
    fallProgress: 0.6,
    depthDistribution: "uniform",
    depthEasing: "quadratic",
    horizonY: 0.3,
  },
  {
    id: "confetti",
    name: "Confetti",
    category: "falling",
    description: "Colorful confetti pieces tumbling chaotically through the air",
    tags: ["celebration", "colorful", "party", "festive"],
    particleType: "petal",
    count: 120,
    sizeMin: 4,
    sizeMax: 10,
    color: "#FF4488",
    colorVariation: 0.5,
    opacity: 0.95,
    windAngle: 20,
    windStrength: 0.35,
    windTurbulence: 0.7,
    fallProgress: 0.55,
    fallSpreadY: 0.8,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.25,
  },
  {
    id: "pine-needles",
    name: "Pine Needles",
    category: "falling",
    description: "Thin pine needles falling from conifers in autumn wind",
    tags: ["pine", "needles", "autumn", "forest", "thin"],
    particleType: "needle",
    count: 100,
    sizeMin: 5,
    sizeMax: 14,
    color: "#4A6B3A",
    colorVariation: 0.15,
    opacity: 0.8,
    windAngle: 10,
    windStrength: 0.25,
    fallProgress: 0.65,
    depthDistribution: "foreground-heavy",
    depthEasing: "linear",
    horizonY: 0.3,
  },
];
