import type { FallingPreset } from "./types.js";

export const FALLING_PRESETS: FallingPreset[] = [
  {
    id: "snow",
    name: "Snow",
    category: "falling",
    description: "Gentle snowfall with mixed flake sizes drifting in light wind",
    tags: ["winter", "snow", "cold", "gentle"],
    particleType: "snowflake",
    count: 200,
    sizeMin: 2,
    sizeMax: 8,
    color: "#FFFFFF",
    colorVariation: 0.05,
    opacity: 0.8,
    windAngle: 15,
    windStrength: 0.3,
    fallProgress: 0.7,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "rain",
    name: "Rain",
    category: "falling",
    description: "Steady rainfall with elongated drops and consistent direction",
    tags: ["rain", "storm", "wet", "dramatic"],
    particleType: "raindrop",
    count: 400,
    sizeMin: 3,
    sizeMax: 10,
    color: "#B0C4DE",
    colorVariation: 0.1,
    opacity: 0.5,
    windAngle: 5,
    windStrength: 0.1,
    fallProgress: 1.0,
    depthDistribution: "uniform",
    depthEasing: "quadratic",
    horizonY: 0.25,
  },
  {
    id: "autumn-leaves",
    name: "Autumn Leaves",
    category: "falling",
    description: "Drifting autumn leaves in warm colors with gentle wind",
    tags: ["autumn", "leaves", "warm", "seasonal"],
    particleType: "leaf",
    count: 60,
    sizeMin: 6,
    sizeMax: 18,
    color: "#C8652A",
    colorVariation: 0.3,
    opacity: 0.9,
    windAngle: 25,
    windStrength: 0.5,
    fallProgress: 0.5,
    depthDistribution: "foreground-heavy",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "petals",
    name: "Cherry Blossom Petals",
    category: "falling",
    description: "Delicate pink petals drifting on a spring breeze",
    tags: ["spring", "petals", "cherry", "delicate"],
    particleType: "petal",
    count: 80,
    sizeMin: 4,
    sizeMax: 12,
    color: "#FFB7C5",
    colorVariation: 0.15,
    opacity: 0.85,
    windAngle: 30,
    windStrength: 0.4,
    fallProgress: 0.4,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.35,
  },
];
