import type { FloatingPreset } from "./types.js";

export const FLOATING_PRESETS: FloatingPreset[] = [
  {
    id: "dust-motes",
    name: "Dust Motes",
    category: "floating",
    description: "Tiny dust particles catching light as they drift in still air",
    tags: ["dust", "light", "indoor", "subtle"],
    particleType: "dot",
    count: 100,
    sizeMin: 1,
    sizeMax: 3,
    color: "#F5DEB3",
    opacity: 0.4,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 5,
    driftPhase: 0,
    depthBandMin: 0.2,
    depthBandMax: 0.8,
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "fireflies",
    name: "Fireflies",
    category: "floating",
    description: "Warm glowing fireflies hovering in the dark with radial glow",
    tags: ["night", "glow", "warm", "magical"],
    particleType: "firefly",
    count: 30,
    sizeMin: 3,
    sizeMax: 8,
    color: "#FFDD44",
    opacity: 0.9,
    glow: true,
    glowColor: "#FFEE88",
    driftRange: 15,
    driftPhase: 0,
    depthBandMin: 0.3,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "fog-wisps",
    name: "Fog Wisps",
    category: "floating",
    description: "Thin curving wisps of fog drifting at mid-height",
    tags: ["fog", "wisp", "atmospheric", "subtle"],
    particleType: "wisp",
    count: 40,
    sizeMin: 8,
    sizeMax: 25,
    color: "#D0D8E0",
    opacity: 0.25,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 20,
    driftPhase: 0,
    depthBandMin: 0.3,
    depthBandMax: 0.7,
    depthEasing: "quadratic",
    horizonY: 0.35,
  },
  {
    id: "pollen",
    name: "Pollen",
    category: "floating",
    description: "Drifting pollen grains floating in warm sunlight",
    tags: ["spring", "pollen", "warm", "nature"],
    particleType: "pollen",
    count: 60,
    sizeMin: 2,
    sizeMax: 5,
    color: "#E8D44D",
    opacity: 0.5,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 8,
    driftPhase: 0,
    depthBandMin: 0.1,
    depthBandMax: 0.6,
    depthEasing: "linear",
    horizonY: 0.35,
  },
  {
    id: "dandelion-seeds",
    name: "Dandelion Seeds",
    category: "floating",
    description: "Wispy dandelion seeds floating on gentle currents",
    tags: ["seeds", "dandelion", "gentle", "summer", "nature"],
    particleType: "seed-tuft",
    count: 25,
    sizeMin: 6,
    sizeMax: 14,
    color: "#F0EDE0",
    opacity: 0.7,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 25,
    driftPhase: 0,
    depthBandMin: 0.15,
    depthBandMax: 0.65,
    depthEasing: "linear",
    horizonY: 0.35,
  },
  {
    id: "butterflies",
    name: "Butterflies",
    category: "floating",
    description: "Colorful butterflies fluttering through a meadow",
    tags: ["butterfly", "nature", "colorful", "summer", "meadow"],
    particleType: "butterfly",
    count: 15,
    sizeMin: 8,
    sizeMax: 18,
    color: "#FF8844",
    opacity: 0.85,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 30,
    driftPhase: 0,
    depthBandMin: 0.2,
    depthBandMax: 0.75,
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "bubbles",
    name: "Bubbles",
    category: "floating",
    description: "Translucent soap bubbles drifting upward with highlights",
    tags: ["bubbles", "transparent", "playful", "light"],
    particleType: "bubble",
    count: 20,
    sizeMin: 5,
    sizeMax: 20,
    color: "#A0D0E8",
    opacity: 0.5,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 12,
    driftPhase: 0,
    depthBandMin: 0.1,
    depthBandMax: 0.8,
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "sparkles",
    name: "Sparkles",
    category: "floating",
    description: "Bright sparkle points twinkling in the air",
    tags: ["sparkle", "glitter", "bright", "magical"],
    particleType: "sparkle",
    count: 50,
    sizeMin: 2,
    sizeMax: 7,
    color: "#FFFFCC",
    opacity: 0.9,
    glow: true,
    glowColor: "#FFFFEE",
    driftRange: 10,
    driftPhase: 0,
    depthBandMin: 0.1,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.3,
  },
];
