import type { FloatingPreset } from "./types.js";

export const FLOATING_PRESETS: FloatingPreset[] = [
  {
    id: "dust-motes",
    name: "Dust Motes",
    category: "floating",
    description: "Tiny dust particles catching light as they drift in still air",
    tags: ["dust", "light", "indoor", "subtle"],
    particleType: "dot",
    count: 100,
    sizeMin: 1,
    sizeMax: 3,
    color: "#F5DEB3",
    opacity: 0.4,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 5,
    driftPhase: 0,
    depthBandMin: 0.2,
    depthBandMax: 0.8,
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "fireflies",
    name: "Fireflies",
    category: "floating",
    description: "Warm glowing fireflies hovering in the dark with radial glow",
    tags: ["night", "glow", "warm", "magical"],
    particleType: "firefly",
    count: 30,
    sizeMin: 3,
    sizeMax: 8,
    color: "#FFDD44",
    opacity: 0.9,
    glow: true,
    glowColor: "#FFEE88",
    driftRange: 15,
    driftPhase: 0,
    depthBandMin: 0.3,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "fog-wisps",
    name: "Fog Wisps",
    category: "floating",
    description: "Thin curving wisps of fog drifting at mid-height",
    tags: ["fog", "wisp", "atmospheric", "subtle"],
    particleType: "wisp",
    count: 40,
    sizeMin: 8,
    sizeMax: 25,
    color: "#D0D8E0",
    opacity: 0.25,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 20,
    driftPhase: 0,
    depthBandMin: 0.3,
    depthBandMax: 0.7,
    depthEasing: "quadratic",
    horizonY: 0.35,
  },
  {
    id: "pollen",
    name: "Pollen",
    category: "floating",
    description: "Drifting pollen grains floating in warm sunlight",
    tags: ["spring", "pollen", "warm", "nature"],
    particleType: "pollen",
    count: 60,
    sizeMin: 2,
    sizeMax: 5,
    color: "#E8D44D",
    opacity: 0.5,
    glow: false,
    glowColor: "#FFFFFF",
    driftRange: 8,
    driftPhase: 0,
    depthBandMin: 0.1,
    depthBandMax: 0.6,
    depthEasing: "linear",
    horizonY: 0.35,
  },
];
