import type { FlowPreset } from "./types.js";

export const FLOW_PRESETS: FlowPreset[] = [
  {
    id: "flow-smoke",
    name: "Smoke Wisps",
    category: "flow",
    description: "Pale grey smoke tendrils curling upward in slow lazy arcs",
    tags: ["smoke", "atmosphere", "grey", "gentle", "indoor"],
    // Many thin wisps drifting upward with curl turbulence
    count: 1200,
    pathSteps: 65,
    stepSize: 0.012,
    noiseScale: 1.4,
    noiseOctaves: 3,
    sizeMin: 0.3,
    sizeMax: 0.9,
    color: "#C8C8C8",
    colorVariation: 0.1,
    opacity: 0.4,
    swirling: 0.22,
    flowAngle: 270,   // upward (-Y in canvas)
    flowStrength: 0.42,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "ink-diffusion",
    name: "Ink Diffusion",
    category: "flow",
    description: "Dark ink ribbons spreading and curling through water — abstract fluid motion",
    tags: ["ink", "water", "abstract", "dark", "dramatic"],
    // Pure curl, no bias — smooth organic tendrils spreading like ink in water
    count: 550,
    pathSteps: 95,
    stepSize: 0.016,
    noiseScale: 1.1,
    noiseOctaves: 4,
    sizeMin: 0.7,
    sizeMax: 2.5,
    color: "#1A1A2E",
    colorVariation: 0.15,
    opacity: 0.72,
    swirling: 0.28,
    flowAngle: 0,
    flowStrength: 0.0,
    depthDistribution: "uniform",
    depthEasing: "quadratic",
    horizonY: 0.5,
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "flow",
    description: "Luminous green-cyan ribbons flowing in long sweeping bands across a dark sky",
    tags: ["aurora", "night", "green", "magical", "sky"],
    // Broad horizontal sweeping bands with gentle vertical curl
    count: 300,
    pathSteps: 150,
    stepSize: 0.022,
    noiseScale: 0.5,
    noiseOctaves: 2,
    sizeMin: 2.5,
    sizeMax: 7.0,
    color: "#44FFAA",
    colorVariation: 0.2,
    opacity: 0.45,
    swirling: 0.08,
    flowAngle: 0,     // rightward
    flowStrength: 0.55,
    depthDistribution: "background-heavy",
    depthEasing: "linear",
    horizonY: 0.2,
  },
  {
    id: "lava-flow",
    name: "Lava Flow",
    category: "flow",
    description: "Slow viscous orange-red rivers of molten rock winding across dark ground",
    tags: ["lava", "fire", "orange", "dramatic", "geological"],
    // Thick downward-flowing rivers with low turbulence
    count: 250,
    pathSteps: 130,
    stepSize: 0.014,
    noiseScale: 0.8,
    noiseOctaves: 3,
    sizeMin: 3.5,
    sizeMax: 9.0,
    color: "#FF4400",
    colorVariation: 0.2,
    opacity: 0.85,
    swirling: 0.06,
    flowAngle: 90,    // downward
    flowStrength: 0.35,
    depthDistribution: "foreground-heavy",
    depthEasing: "quadratic",
    horizonY: 0.6,
  },
  {
    id: "water-current",
    name: "Water Current",
    category: "flow",
    description: "Blue-white water flow lines tracing the movement of a shallow stream",
    tags: ["water", "river", "blue", "natural", "gentle"],
    // Many thin horizontal streamlines with light turbulence
    count: 1100,
    pathSteps: 100,
    stepSize: 0.019,
    noiseScale: 0.85,
    noiseOctaves: 3,
    sizeMin: 0.3,
    sizeMax: 1.2,
    color: "#80C8E8",
    colorVariation: 0.12,
    opacity: 0.5,
    swirling: 0.05,
    flowAngle: 0,     // rightward
    flowStrength: 0.6,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "wind-streams",
    name: "Wind Streams",
    category: "flow",
    description: "Fine white-grey streamlines visualising wind sweeping across an open landscape",
    tags: ["wind", "air", "white", "subtle", "landscape"],
    // Many very fine lines flowing rightward
    count: 1600,
    pathSteps: 80,
    stepSize: 0.024,
    noiseScale: 0.9,
    noiseOctaves: 2,
    sizeMin: 0.2,
    sizeMax: 0.7,
    color: "#E8EEF4",
    colorVariation: 0.06,
    opacity: 0.4,
    swirling: 0.0,
    flowAngle: 0,     // rightward
    flowStrength: 0.7,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.35,
  },
];
