import type { FlowPreset } from "./types.js";

export const FLOW_PRESETS: FlowPreset[] = [
  {
    id: "flow-smoke",
    name: "Smoke Wisps",
    category: "flow",
    description: "Pale grey smoke tendrils curling upward in slow lazy arcs",
    tags: ["smoke", "atmosphere", "grey", "gentle", "indoor"],
    count: 60,
    pathSteps: 80,
    stepSize: 0.018,
    noiseScale: 1.2,
    noiseOctaves: 3,
    sizeMin: 0.8,
    sizeMax: 2.5,
    color: "#C8C8C8",
    colorVariation: 0.08,
    opacity: 0.55,
    swirling: 0.15,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "ink-diffusion",
    name: "Ink Diffusion",
    category: "flow",
    description: "Dark ink ribbons spreading and curling through water — abstract fluid motion",
    tags: ["ink", "water", "abstract", "dark", "dramatic"],
    count: 40,
    pathSteps: 100,
    stepSize: 0.022,
    noiseScale: 1.8,
    noiseOctaves: 4,
    sizeMin: 1.0,
    sizeMax: 3.5,
    color: "#1A1A2E",
    colorVariation: 0.12,
    opacity: 0.7,
    swirling: 0.25,
    depthDistribution: "uniform",
    depthEasing: "quadratic",
    horizonY: 0.5,
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "flow",
    description: "Luminous green-cyan ribbons flowing in long sweeping bands across a dark sky",
    tags: ["aurora", "night", "green", "magical", "sky"],
    count: 25,
    pathSteps: 140,
    stepSize: 0.025,
    noiseScale: 0.7,
    noiseOctaves: 2,
    sizeMin: 2.0,
    sizeMax: 6.0,
    color: "#44FFAA",
    colorVariation: 0.18,
    opacity: 0.5,
    swirling: 0.05,
    depthDistribution: "background-heavy",
    depthEasing: "linear",
    horizonY: 0.2,
  },
  {
    id: "lava-flow",
    name: "Lava Flow",
    category: "flow",
    description: "Slow viscous orange-red rivers of molten rock winding across dark ground",
    tags: ["lava", "fire", "orange", "dramatic", "geological"],
    count: 20,
    pathSteps: 120,
    stepSize: 0.015,
    noiseScale: 0.9,
    noiseOctaves: 3,
    sizeMin: 3.0,
    sizeMax: 8.0,
    color: "#FF4400",
    colorVariation: 0.2,
    opacity: 0.8,
    swirling: 0.1,
    depthDistribution: "foreground-heavy",
    depthEasing: "quadratic",
    horizonY: 0.6,
  },
  {
    id: "water-current",
    name: "Water Current",
    category: "flow",
    description: "Blue-white water flow lines tracing the movement of a shallow stream",
    tags: ["water", "river", "blue", "natural", "gentle"],
    count: 80,
    pathSteps: 90,
    stepSize: 0.02,
    noiseScale: 1.4,
    noiseOctaves: 3,
    sizeMin: 0.5,
    sizeMax: 1.8,
    color: "#80C8E8",
    colorVariation: 0.1,
    opacity: 0.45,
    swirling: 0.08,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "wind-streams",
    name: "Wind Streams",
    category: "flow",
    description: "Fine white-grey streamlines visualising wind sweeping across an open landscape",
    tags: ["wind", "air", "white", "subtle", "landscape"],
    count: 120,
    pathSteps: 70,
    stepSize: 0.028,
    noiseScale: 1.0,
    noiseOctaves: 2,
    sizeMin: 0.4,
    sizeMax: 1.2,
    color: "#E8EEF4",
    colorVariation: 0.06,
    opacity: 0.35,
    swirling: 0.0,
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.35,
  },
];
