import type { MarkFieldPreset } from "./types.js";

export const MARK_FIELD_PRESETS: MarkFieldPreset[] = [
  {
    id: "grass-blades",
    name: "Grass Blades",
    category: "mark-field",
    description: "Fine upward-angled ink strokes mimicking a field of grass — narrow and densely packed",
    tags: ["grass", "nature", "green", "dense", "field"],
    count: 400,
    markLength: 0.04,
    markWidth: 1.2,
    angle: -80,
    angleVariation: 20,
    curvature: 0.3,
    markStyle: "ink",
    color: "#3A6B2A",
    colorVariation: 0.15,
    opacity: 0.75,
    depthBandMin: 0.3,
    depthBandMax: 0.95,
    depthEasing: "quadratic",
    horizonY: 0.45,
  },
  {
    id: "reed-field",
    name: "Reed Field",
    category: "mark-field",
    description: "Tall slender reeds in warm ochre — sparse, slightly curved, standing upright",
    tags: ["reeds", "wetland", "ochre", "sparse", "vertical"],
    count: 120,
    markLength: 0.09,
    markWidth: 1.8,
    angle: -85,
    angleVariation: 8,
    curvature: 0.2,
    markStyle: "ink",
    color: "#C8A050",
    colorVariation: 0.18,
    opacity: 0.8,
    depthBandMin: 0.2,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.4,
  },
  {
    id: "ink-scatter",
    name: "Ink Scatter",
    category: "mark-field",
    description: "Random-angle short ink strokes scattered across the canvas — loose gestural texture",
    tags: ["ink", "abstract", "texture", "gestural", "random"],
    count: 300,
    markLength: 0.025,
    markWidth: 1.5,
    angle: 0,
    angleVariation: 180,
    curvature: 0.1,
    markStyle: "ink",
    color: "#1C1C1C",
    colorVariation: 0.05,
    opacity: 0.6,
    depthBandMin: 0.1,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.5,
  },
  {
    id: "dry-brush",
    name: "Dry Brush",
    category: "mark-field",
    description: "Wide horizontal brush strokes with rough edges — painterly textured surface effect",
    tags: ["brush", "texture", "painterly", "horizontal", "rough"],
    count: 150,
    markLength: 0.06,
    markWidth: 3.5,
    angle: 5,
    angleVariation: 12,
    curvature: 0.15,
    markStyle: "brush",
    color: "#8B6040",
    colorVariation: 0.12,
    opacity: 0.55,
    depthBandMin: 0.15,
    depthBandMax: 0.85,
    depthEasing: "linear",
    horizonY: 0.45,
  },
  {
    id: "charcoal-scatter",
    name: "Charcoal Scatter",
    category: "mark-field",
    description: "Soft grey pencil marks scattered at varied angles — charcoal drawing surface texture",
    tags: ["charcoal", "pencil", "grey", "soft", "texture"],
    count: 250,
    markLength: 0.035,
    markWidth: 2.0,
    angle: -30,
    angleVariation: 60,
    curvature: 0.08,
    markStyle: "pencil",
    color: "#505050",
    colorVariation: 0.1,
    opacity: 0.45,
    depthBandMin: 0.1,
    depthBandMax: 0.9,
    depthEasing: "linear",
    horizonY: 0.5,
  },
  {
    id: "calligraphy-marks",
    name: "Calligraphy Marks",
    category: "mark-field",
    description: "Bold diagonal calligraphic strokes — thick tapered marks suggesting brushed script",
    tags: ["calligraphy", "brush", "bold", "diagonal", "artistic"],
    count: 80,
    markLength: 0.055,
    markWidth: 4.0,
    angle: -45,
    angleVariation: 25,
    curvature: 0.35,
    markStyle: "brush",
    color: "#111111",
    colorVariation: 0.08,
    opacity: 0.85,
    depthBandMin: 0.1,
    depthBandMax: 0.9,
    depthEasing: "quadratic",
    horizonY: 0.5,
  },
];
