import type { MistPreset } from "./types.js";

export const MIST_PRESETS: MistPreset[] = [
  {
    id: "morning-mist",
    name: "Morning Mist",
    category: "mist",
    description: "Soft white mist hovering low in the morning light with gentle drift",
    tags: ["morning", "soft", "white", "low"],
    density: 0.4,
    color: "#E8E8F0",
    opacity: 0.35,
    bandTop: 0.5,
    bandBottom: 0.8,
    edgeSoftness: 0.3,
    noiseScale: 3.0,
    noiseOctaves: 3,
    driftX: 0.1,
    driftPhase: 0,
    layerCount: 3,
    depthSpread: 0.2,
  },
  {
    id: "valley-fog",
    name: "Valley Fog",
    category: "mist",
    description: "Dense fog filling a valley floor with layered depth and soft edges",
    tags: ["dense", "valley", "fog", "cold"],
    density: 0.7,
    color: "#D0D0D8",
    opacity: 0.5,
    bandTop: 0.4,
    bandBottom: 0.9,
    edgeSoftness: 0.2,
    noiseScale: 2.5,
    noiseOctaves: 4,
    driftX: 0.05,
    driftPhase: 0,
    layerCount: 5,
    depthSpread: 0.3,
  },
  {
    id: "mountain-haze",
    name: "Mountain Haze",
    category: "mist",
    description: "Thin atmospheric haze across a wide elevation range with subtle noise",
    tags: ["thin", "atmospheric", "mountain", "wide"],
    density: 0.25,
    color: "#C8D0E0",
    opacity: 0.2,
    bandTop: 0.2,
    bandBottom: 0.7,
    edgeSoftness: 0.4,
    noiseScale: 4.0,
    noiseOctaves: 2,
    driftX: 0.15,
    driftPhase: 0,
    layerCount: 2,
    depthSpread: 0.15,
  },
  {
    id: "ground-steam",
    name: "Ground Steam",
    category: "mist",
    description: "Rising steam from warm ground with tight low band and vertical drift",
    tags: ["steam", "warm", "rising", "narrow"],
    density: 0.5,
    color: "#F0F0F0",
    opacity: 0.3,
    bandTop: 0.65,
    bandBottom: 0.95,
    edgeSoftness: 0.15,
    noiseScale: 5.0,
    noiseOctaves: 3,
    driftX: 0.02,
    driftPhase: 0,
    layerCount: 4,
    depthSpread: 0.1,
  },
];
