import type { MistPreset } from "./types.js";

export const MIST_PRESETS: MistPreset[] = [
  {
    id: "morning-mist",
    name: "Morning Mist",
    category: "mist",
    description: "Soft mist hovering low in morning light, cool-white top fading to warm gold at the base",
    tags: ["morning", "soft", "white", "low"],
    density: 0.4,
    color: "#E8E8F0",
    colorBottom: "#F0E8D0",
    opacity: 0.35,
    bandTop: 0.5,
    bandBottom: 0.8,
    edgeSoftness: 0.3,
    noiseScale: 3.0,
    noiseOctaves: 3,
    driftX: 0.1,
    driftY: 0,
    driftPhase: 0,
    layerCount: 3,
    depthSpread: 0.2,
  },
  {
    id: "valley-fog",
    name: "Valley Fog",
    category: "mist",
    description: "Dense fog filling a valley floor with layered depth and soft edges",
    tags: ["dense", "valley", "fog", "cold"],
    density: 0.7,
    color: "#D0D0D8",
    opacity: 0.5,
    bandTop: 0.4,
    bandBottom: 0.9,
    edgeSoftness: 0.2,
    noiseScale: 2.5,
    noiseOctaves: 4,
    driftX: 0.05,
    driftPhase: 0,
    layerCount: 5,
    depthSpread: 0.3,
  },
  {
    id: "mountain-haze",
    name: "Mountain Haze",
    category: "mist",
    description: "Thin atmospheric haze across a wide elevation range with subtle noise",
    tags: ["thin", "atmospheric", "mountain", "wide"],
    density: 0.25,
    color: "#C8D0E0",
    opacity: 0.2,
    bandTop: 0.2,
    bandBottom: 0.7,
    edgeSoftness: 0.4,
    noiseScale: 4.0,
    noiseOctaves: 2,
    driftX: 0.15,
    driftPhase: 0,
    layerCount: 2,
    depthSpread: 0.15,
  },
  {
    id: "ground-steam",
    name: "Ground Steam",
    category: "mist",
    description: "Rising steam from warm ground with tight low band and vertical drift",
    tags: ["steam", "warm", "rising", "narrow"],
    density: 0.5,
    color: "#F0F0F0",
    colorBottom: "#F8F0E0",
    opacity: 0.3,
    bandTop: 0.65,
    bandBottom: 0.95,
    edgeSoftness: 0.15,
    noiseScale: 5.0,
    noiseOctaves: 3,
    driftX: 0.02,
    driftY: -0.25,
    driftPhase: 0,
    layerCount: 4,
    depthSpread: 0.1,
  },
  {
    id: "ground-steam-thick",
    name: "Ground Steam (Thick)",
    category: "mist",
    description: "Dense billowing steam rising from hot ground with heavy layering",
    tags: ["steam", "dense", "hot", "rising", "thick"],
    density: 0.75,
    color: "#F0F0F0",
    colorBottom: "#F0EAD8",
    opacity: 0.45,
    bandTop: 0.55,
    bandBottom: 0.95,
    edgeSoftness: 0.2,
    noiseScale: 4.0,
    noiseOctaves: 4,
    driftX: 0.05,
    driftY: -0.3,
    driftPhase: 0,
    layerCount: 6,
    depthSpread: 0.15,
  },
  {
    id: "smoke-wisps",
    name: "Smoke Wisps",
    category: "mist",
    description: "Thin wisps of smoke curling upward with organic noise patterns",
    tags: ["smoke", "wisps", "organic", "dark", "rising"],
    density: 0.35,
    color: "#A0A0A8",
    opacity: 0.3,
    bandTop: 0.3,
    bandBottom: 0.75,
    edgeSoftness: 0.35,
    noiseScale: 6.0,
    noiseOctaves: 3,
    driftX: 0.08,
    driftPhase: 0,
    layerCount: 3,
    depthSpread: 0.25,
  },
];
