import type { ScatterPreset } from "./types.js";

export const SCATTER_PRESETS: ScatterPreset[] = [
  {
    id: "fallen-leaves",
    name: "Fallen Leaves",
    category: "scatter",
    description: "Autumn leaves scattered on the ground with warm color variation",
    tags: ["autumn", "leaves", "ground", "warm"],
    elementType: "leaf",
    count: 80,
    sizeMin: 8,
    sizeMax: 22,
    color: "#B8652A",
    colorVariation: 0.35,
    rotationRange: Math.PI * 2,
    distribution: "clustered",
    clusterStrength: 0.4,
    groundY: 0.7,
    horizonY: 0.35,
    depthEasing: "quadratic",
  },
  {
    id: "pebbles",
    name: "Pebbles",
    category: "scatter",
    description: "Small stones scattered across a ground plane with natural clustering",
    tags: ["stones", "ground", "natural", "neutral"],
    elementType: "stone",
    count: 60,
    sizeMin: 3,
    sizeMax: 12,
    color: "#8A8A80",
    colorVariation: 0.2,
    rotationRange: Math.PI * 2,
    distribution: "uniform",
    clusterStrength: 0,
    groundY: 0.75,
    horizonY: 0.35,
    depthEasing: "quadratic",
  },
  {
    id: "wildflowers",
    name: "Wildflowers",
    category: "scatter",
    description: "Colorful wildflowers dotting a meadow with center-weighted density",
    tags: ["flowers", "meadow", "colorful", "spring"],
    elementType: "flower",
    count: 50,
    sizeMin: 5,
    sizeMax: 15,
    color: "#E05090",
    colorVariation: 0.4,
    rotationRange: Math.PI * 0.5,
    distribution: "center-weighted",
    clusterStrength: 0,
    groundY: 0.65,
    horizonY: 0.3,
    depthEasing: "quadratic",
  },
  {
    id: "shells",
    name: "Shells",
    category: "scatter",
    description: "Seashells scattered along a beach shore",
    tags: ["beach", "shells", "ocean", "shore", "coastal"],
    elementType: "shell",
    count: 40,
    sizeMin: 5,
    sizeMax: 16,
    color: "#E8D5B8",
    colorVariation: 0.25,
    rotationRange: Math.PI * 2,
    distribution: "uniform",
    clusterStrength: 0,
    groundY: 0.75,
    horizonY: 0.35,
    depthEasing: "quadratic",
  },
  {
    id: "acorns",
    name: "Acorns",
    category: "scatter",
    description: "Acorns scattered beneath oak trees in clustered groups",
    tags: ["acorns", "autumn", "forest", "nuts", "ground"],
    elementType: "acorn",
    count: 45,
    sizeMin: 4,
    sizeMax: 10,
    color: "#7B5B3A",
    colorVariation: 0.15,
    rotationRange: Math.PI * 2,
    distribution: "clustered",
    clusterStrength: 0.5,
    groundY: 0.72,
    horizonY: 0.35,
    depthEasing: "quadratic",
  },
  {
    id: "sea-foam",
    name: "Sea Foam",
    category: "scatter",
    description: "Foamy bubbles along a shoreline edge",
    tags: ["ocean", "foam", "beach", "water", "shore"],
    elementType: "debris",
    count: 70,
    sizeMin: 3,
    sizeMax: 10,
    color: "#F0F8FF",
    colorVariation: 0.1,
    rotationRange: Math.PI * 2,
    distribution: "edge-weighted",
    clusterStrength: 0,
    groundY: 0.8,
    horizonY: 0.4,
    depthEasing: "linear",
  },
];
