import type { TrailingPreset } from "./types.js";

export const TRAILING_PRESETS: TrailingPreset[] = [
  {
    id: "meteor-shower",
    name: "Meteor Shower",
    category: "trailing",
    description: "Blue-white meteors streaking southeast across a night sky with glowing heads",
    tags: ["space", "night", "dramatic", "meteor", "stars"],
    count: 80,
    sizeMin: 1,
    sizeMax: 3,
    trailLength: 0.15,
    motionAngle: 45,
    motionVariation: 12,
    color: "#C8D8FF",
    colorVariation: 0.1,
    opacity: 0.85,
    glow: true,
    glowColor: "#FFFFFF",
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "speed-rain",
    name: "Speed Rain",
    category: "trailing",
    description: "Dense near-vertical rain streaks with depth — foreground drops larger than background",
    tags: ["rain", "storm", "wet", "dramatic", "speed"],
    count: 250,
    sizeMin: 0.5,
    sizeMax: 2,
    trailLength: 0.12,
    motionAngle: 85,
    motionVariation: 4,
    color: "#B0C4DE",
    colorVariation: 0.08,
    opacity: 0.6,
    glow: false,
    glowColor: "#FFFFFF",
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "shooting-stars",
    name: "Shooting Stars",
    category: "trailing",
    description: "Warm golden shooting stars arcing southwest with soft glowing heads",
    tags: ["space", "night", "stars", "romantic", "gentle"],
    count: 40,
    sizeMin: 1,
    sizeMax: 4,
    trailLength: 0.2,
    motionAngle: 135,
    motionVariation: 18,
    color: "#FFE8A0",
    colorVariation: 0.12,
    opacity: 0.9,
    glow: true,
    glowColor: "#FFFFD0",
    depthDistribution: "uniform",
    depthEasing: "linear",
    horizonY: 0.3,
  },
  {
    id: "light-trails",
    name: "Light Trails",
    category: "trailing",
    description: "Horizontal warm light streaks moving across the frame — long exposure bokeh effect",
    tags: ["abstract", "light", "bokeh", "modern", "horizontal"],
    count: 60,
    sizeMin: 0.5,
    sizeMax: 3,
    trailLength: 0.25,
    motionAngle: 0,
    motionVariation: 6,
    color: "#FFF8D0",
    colorVariation: 0.15,
    opacity: 0.7,
    glow: true,
    glowColor: "#FFFFFF",
    depthDistribution: "midground",
    depthEasing: "quadratic",
    horizonY: 0.4,
  },
  {
    id: "rising-sparks",
    name: "Rising Sparks",
    category: "trailing",
    description: "Orange-red sparks and embers rising upward in a spreading fan",
    tags: ["fire", "sparks", "embers", "warm", "rising"],
    count: 120,
    sizeMin: 0.5,
    sizeMax: 2.5,
    trailLength: 0.08,
    motionAngle: 270,
    motionVariation: 35,
    color: "#FF6030",
    colorVariation: 0.2,
    opacity: 0.8,
    glow: true,
    glowColor: "#FFAA20",
    depthDistribution: "foreground-heavy",
    depthEasing: "quadratic",
    horizonY: 0.5,
  },
];
